# H2 Database Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datasource Configuration
spring.datasource.url=jdbc:h2:mem:aircraftdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.security.oauth2.client.registration.github.client-id=Ov23liOoBXNjhTMJJXsH
spring.security.oauth2.client.registration.github.client-secret=f1401e0ad33da0e237d9a6e265d1ff7e989122b6